### ISSUE TITLE
db/migrate.cr file not created on kgen init app appname

### ISSUE THREAD

**Issue by bjornforsberg** [kemalyst/kemalyst#30]
Hey Guys,

Thanks for building this framework, looks really promising for someone used to working with ruby/rails like me 👍 

I'm trying to get my first project going with it, and when I run the command:

```
kgen init app appname
```
Then it is not creating the db folder or the migrate.cr file

Here's the commands I ran to get things going.

Firstly grab the generator:

```
MacBook-Pro:~ FORSBERGtwo$ git clone git@github.com:TechMagister/kemalyst-generator.git
Cloning into 'kemalyst-generator'...
Enter passphrase for key '/Users/FORSBERGtwo/.ssh/id_rsa':
remote: Counting objects: 781, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 781 (delta 4), reused 0 (delta 0), pack-reused 766
Receiving objects: 100% (781/781), 84.66 KiB | 0 bytes/s, done.
Resolving deltas: 100% (346/346), done.
MacBook-Pro:~ FORSBERGtwo$ cd kemalyst-generator/
MacBook-Pro:kemalyst-generator FORSBERGtwo$ shards install
Updating https://github.com/mosop/cli.git
Updating https://github.com/mosop/optarg.git
Updating https://github.com/mosop/callback.git
Updating https://github.com/mosop/string_inflection.git
Updating https://github.com/mosop/teeplate.git
Updating https://github.com/TechMagister/crystal-icr.git
Updating https://github.com/TechMagister/sentry.git
Updating https://github.com/juanedi/micrate.git
Updating https://github.com/crystal-lang/crystal-db.git
Updating https://github.com/will/crystal-pg.git
Updating https://github.com/crystal-lang/crystal-mysql.git
Updating https://github.com/crystal-lang/crystal-sqlite3.git
Installing cli (0.5.2)
Installing optarg (0.4.4)
Installing callback (0.5.1)
Installing string_inflection (0.2.0)
Installing teeplate (0.2.3)
Installing icr (fea1ddd02c8becdced0cb1a049c62b42e7aaa63d)
Installing sentry (a78129ec1e66aa24c91b93199ea187e4793c8d58)
Installing micrate (0.3.0)
Installing db (0.4.0)
Installing pg (0.13.3)
Installing mysql (0.3.2)
Installing sqlite3 (0.8.2)
MacBook-Pro:kemalyst-generator FORSBERGtwo$ make
Building kgen in /Users/FORSBERGtwo/kemalyst-generator
MacBook-Pro:kemalyst-generator FORSBERGtwo$ ln -sf $(pwd)/bin/kgen /usr/local/bin/kgen
MacBook-Pro:kemalyst-generator FORSBERGtwo$ cd
```

Then I ran the init app  instructions:

```
MacBook-Pro:~ FORSBERGtwo$ kgen init app orderlylinks
Rendering App orderlylinks in ./orderlylinks
 - creating .gitignore
 - creating .travis.yml
 - creating bin/sentry.cr
 - creating config/application.cr
 - creating config/database.yml
 - creating config/routes.cr
 - creating config/session.cr
 - creating config/static.cr
 - creating docker-compose.yml
 - creating Dockerfile
 - creating LICENSE
 - creating public/crossdomain.xml
 - creating public/javascripts/main.js
 - creating public/robots.txt
 - creating public/stylesheets/main.css
 - creating README.md
 - creating shard.yml
 - creating spec/spec_helper.cr
 - creating src/controllers/static_controller.cr
 - creating src/views/layouts/_nav.slang
 - creating src/views/layouts/main.slang
 - creating src/views/static/index.slang
 - creating src/orderlylinks.cr
MacBook-Pro:~ FORSBERGtwo$ cd orderlylinks
MacBook-Pro:orderlylinks FORSBERGtwo$ shards update
Updating https://github.com/drujensen/kemalyst.git
Updating https://github.com/drujensen/kemalyst-model.git
Updating https://github.com/crystal-lang/crystal-db.git
Updating https://github.com/drujensen/kemalyst-validators.git
Updating https://github.com/drujensen/kemalyst-spec.git
Updating https://github.com/drujensen/delimiter_tree.git
Updating https://github.com/jeromegn/kilt.git
Updating https://github.com/jeromegn/slang.git
Updating https://github.com/raydf/smtp.cr.git
Updating https://github.com/will/crystal-pg.git
Updating https://github.com/waterlink/mocks.cr.git
Updating https://github.com/waterlink/singleton.cr.git
Installing kemalyst (0.4.3)
Installing kemalyst-model (0.4.4)
Installing db (0.4.0)
Installing kemalyst-validators (0.2.0)
Installing kemalyst-spec (0.1.1)
Installing delimiter_tree (0.1.4)
Installing kilt (0.3.3)
Installing slang (master)
Installing smtp (master)
Installing pg (0.13.3)
Installing mocks (0.9.4)
Installing singleton (1.0.0)
MacBook-Pro:orderlylinks FORSBERGtwo$
```

Notice there is no creation of db/ or /db/migrate.cr. If I continue the instructions for generating a scaffold and then run the migration I get:

```
MacBook-Pro:orderlylinks FORSBERGtwo$ kgen generate scaffold Shop url:string token:string
Rendering Scaffold shop
 - appending config/routes.cr
 - creating db/migrations/20170331123501_create_shop.sql
 - creating spec/controllers/spec_helper.cr
 - creating spec/controllers/shop_controller_spec.cr
 - creating spec/models/spec_helper.cr
 - creating spec/models/shop_spec.cr
 - creating src/controllers/shop_controller.cr
 - creating src/models/shop.cr
 - appending src/views/layouts/_nav.slang
 - creating src/views/shop/_form.slang
 - creating src/views/shop/edit.slang
 - creating src/views/shop/index.slang
 - creating src/views/shop/new.slang
 - creating src/views/shop/show.slang
MacBook-Pro:orderlylinks FORSBERGtwo$ crystal db/migrate.cr
Error: unknown command: db/migrate.cr
```
Note: I created the DB in Postgres and exported the DATABASE_URL before doing this.

Any ideas? Perhaps related to the upgrade of the crystal-db version yesterday?

OSX Version 10.12.4
shard.lock file below:
````
version: 1.0
shards:
  db:
    github: crystal-lang/crystal-db
    version: 0.4.0

  delimiter_tree:
    github: drujensen/delimiter_tree
    version: 0.1.4

  kemalyst:
    github: drujensen/kemalyst
    version: 0.4.3

  kemalyst-model:
    github: drujensen/kemalyst-model
    version: 0.4.4

  kemalyst-spec:
    github: drujensen/kemalyst-spec
    version: 0.1.1

  kemalyst-validators:
    github: drujensen/kemalyst-validators
    version: 0.2.0

  kilt:
    github: jeromegn/kilt
    version: 0.3.3

  mocks:
    github: waterlink/mocks.cr
    version: 0.9.4

  pg:
    github: will/crystal-pg
    version: 0.13.3

  singleton:
    github: waterlink/singleton.cr
    version: 1.0.0

  slang:
    github: jeromegn/slang
    commit: 17ee48438f9798ac0d47520c47c17bcd7e06cd93

  smtp:
    github: raydf/smtp.cr
    commit: 1301f244fd1e251244b0a9fb7f8bc817da9c8854
````
Many thanks again, can't wait to get more into this 😃
